ModelViewer: ModelManager Class Reference
ModelManager Class Reference final
#include <ModelManager.hpp>
Signals
void geometryChanged ()
void loadingChanged ()
void readyChanged ()
Public Member Functions
ModelManager (QObject *parent=nullptr)
~ModelManager () override=default
QQuick3DGeometry * geometry () const
Q_INVOKABLE void loadModel (const QString &filepath)
bool isLoading () const
void setLoading (bool isLoading)
bool isReady () const
void setReady (bool isReady)
Properties
QQuick3DGeometry * geometry
bool loading
bool ready
Private Attributes
ObjLoader _objLoader
std::unordered_map< std::string, ILoader * > _loaders
ILoader * _lastLoaded = &_objLoader
std::unique_ptr< ObjGeometry > _geometry
bool _loading = false
bool _ready = false
Constructor & Destructor Documentation
ModelManager()
ModelManager::ModelManager (QObject * parent = nullptr) explicit
: QObject(parent) {}
~ModelManager()
ModelManager::~ModelManager () override default
Member Function Documentation
geometry()
QQuick3DGeometry * ModelManager::geometry () const inline
{ return _lastLoaded->geometry(); };
References _lastLoaded, and ILoader::geometry().
geometryChanged
void ModelManager::geometryChanged () signal
Referenced by loadModel().
isLoading()
bool ModelManager::isLoading () const inline
{ return _loading; };
References _loading.
Referenced by setLoading().
isReady()
bool ModelManager::isReady () const inline
{ return _ready; };
References _ready.
Referenced by setReady().
loadingChanged
void ModelManager::loadingChanged () signal
Referenced by setLoading().
loadModel()
void ModelManager::loadModel (const QString & filepath)
{
    const std::string str_path =
        filepath.toStdString().substr(sizeof("file://") - 1);
    const auto pos = str_path.find_last_of('.');
    const std::string ext = str_path.substr(pos);
    auto result = QtConcurrent::run([&, str_path, ext] {
        setReady(false);
        _loaders[ext]->loadModel(str_path);
        emit geometryChanged();
        _lastLoaded = _loaders[ext];
        setReady(true);
    });
}
References _lastLoaded, _loaders, geometryChanged(), and setReady().
readyChanged
void ModelManager::readyChanged () signal
Referenced by setReady().
setLoading()
void ModelManager::setLoading (bool isLoading)
{
    _loading = isLoading;
    emit loadingChanged();
}
References _loading, isLoading(), and loadingChanged().
Referenced by setReady().
setReady()
void ModelManager::setReady (bool isReady)
{
    _ready = isReady;
    emit readyChanged();
    setLoading(!isReady);
}
References _ready, isReady(), readyChanged(), and setLoading().
Referenced by loadModel().
Member Data Documentation
_geometry
std::unique_ptr<ObjGeometry> ModelManager::_geometry private
_lastLoaded
ILoader* ModelManager::_lastLoaded = &_objLoader private
Referenced by geometry(), and loadModel().
_loaders
std::unordered_map<std::string, ILoader *> ModelManager::_loaders private
Initial value:
= {
        {".obj", &_objLoader},
    }
{
        {".obj", &_objLoader},
    };
Referenced by loadModel().
_loading
bool ModelManager::_loading = false private
Referenced by isLoading(), and setLoading().
_objLoader
ObjLoader ModelManager::_objLoader private
_ready
bool ModelManager::_ready = false private
Referenced by isReady(), and setReady().
Property Documentation
geometry
QQuick3DGeometry * ModelManager::geometry read
loading
bool ModelManager::loading read
ready
bool ModelManager::ready read
The documentation for this class was generated from the following files:
/github/workspace/include/ModelManager.hpp
/github/workspace/src/ModelManager.cpp