ModelViewer: model_viewer::ModelManager Class Reference
model_viewer::ModelManager Class Reference final
Class for managing model loading and providing geometry and material.
#include <ModelManager.hpp>
Signals
void geometryChanged ()
Signal emitted when the geometry changes.
void materialChanged ()
Signal emitted when the material changes.
void loadingChanged ()
Signal emitted when the loading state changes.
void readyChanged ()
Signal emitted when the ready state changes.
Public Member Functions
ModelManager (QObject *parent=nullptr)
Constructor.
~ModelManager () override=default
Destructor.
QQuick3DGeometry * geometry () const
Get the geometry of the loaded model.
material::MTLMaterial * material () const
Get the material of the loaded model.
Q_INVOKABLE void loadModel (const QString &filepath)
Load a model from a file asynchronously.
bool isLoading () const
Check if a model is currently loading.
void setLoading (bool isLoading)
Set the loading state, emits loadingChanged signal.
bool isReady () const
Check if a model is ready.
void setReady (bool isReady)
Set the ready state, emits readyChanged signal.
Properties
QQuick3DGeometry * geometry
model_viewer::material::MTLMaterial * material
bool loading
bool ready
Private Attributes
loaders::ObjLoader _objLoader
OBJ loader instance.
std::unordered_map< std::string, loaders::ILoader * > _loaders
Map of file extensions to their respective loaders.
loaders::ILoader * _lastLoaded = &_objLoader
Pointer to the last used loader.
std::unique_ptr< geometry::ObjGeometry > _geometry
Geometry of the currently loaded model.
bool _loading = false
Boolean indicating if a model is currently loading.
bool _ready = false
Boolean indicating if a model is ready.
Detailed Description
Class for managing model loading and providing geometry and material.
Constructor & Destructor Documentation
ModelManager()
model_viewer::ModelManager::ModelManager (QObject * parent = nullptr) explicit
Constructor.
Parameters
parent Parent QObject, nullptr by default
: QObject(parent) {}
~ModelManager()
model_viewer::ModelManager::~ModelManager () override default
Destructor.
Member Function Documentation
geometry()
QQuick3DGeometry * model_viewer::ModelManager::geometry () const inline
Get the geometry of the loaded model.
Returns
Geometry of the loaded model
{ return _lastLoaded->geometry(); };
References _lastLoaded, and model_viewer::loaders::ILoader::geometry().
geometryChanged
void model_viewer::ModelManager::geometryChanged () signal
Signal emitted when the geometry changes.
Referenced by loadModel().
isLoading()
bool model_viewer::ModelManager::isLoading () const inline
Check if a model is currently loading.
Returns
True if a model is loading, false otherwise
{ return _loading; };
References _loading.
Referenced by setLoading().
isReady()
bool model_viewer::ModelManager::isReady () const inline
Check if a model is ready.
Returns
True if a model is ready, false otherwise
{ return _ready; };
References _ready.
Referenced by setReady().
loadingChanged
void model_viewer::ModelManager::loadingChanged () signal
Signal emitted when the loading state changes.
Referenced by setLoading().
loadModel()
void model_viewer::ModelManager::loadModel (const QString & filepath)
Load a model from a file asynchronously.
Emits geometryChanged and materialChanged signals upon completion and is invokable from QML
Parameters
filepath Path to the model file
{
    const std::string strPath =
        filepath.toStdString().substr(sizeof("file://") - 1);
    const auto pos = strPath.find_last_of('.');
    const std::string ext = strPath.substr(pos);
    auto result = QtConcurrent::run([&, strPath, ext] {
        setReady(false);
        _loaders[ext]->loadModel(strPath);
        emit geometryChanged();
        emit materialChanged();
        _lastLoaded = _loaders[ext];
        setReady(true);
    });
}
References _lastLoaded, _loaders, geometryChanged(), materialChanged(), and setReady().
material()
material::MTLMaterial * model_viewer::ModelManager::material () const inline
Get the material of the loaded model.
Returns
Material of the loaded model
{ return _lastLoaded->material(); };
References _lastLoaded, and model_viewer::loaders::ILoader::material().
materialChanged
void model_viewer::ModelManager::materialChanged () signal
Signal emitted when the material changes.
Referenced by loadModel().
readyChanged
void model_viewer::ModelManager::readyChanged () signal
Signal emitted when the ready state changes.
Referenced by setReady().
setLoading()
void model_viewer::ModelManager::setLoading (bool isLoading)
Set the loading state, emits loadingChanged signal.
Parameters
isLoading New loading state
{
    _loading = isLoading;
    emit loadingChanged();
}
References _loading, isLoading(), and loadingChanged().
Referenced by setReady().
setReady()
void model_viewer::ModelManager::setReady (bool isReady)
Set the ready state, emits readyChanged signal.
Parameters
isReady New ready state
{
    _ready = isReady;
    emit readyChanged();
    setLoading(!isReady);
}
References _ready, isReady(), readyChanged(), and setLoading().
Referenced by loadModel().
Member Data Documentation
_geometry
std::unique_ptr<geometry::ObjGeometry> model_viewer::ModelManager::_geometry private
Geometry of the currently loaded model.
_lastLoaded
loaders::ILoader* model_viewer::ModelManager::_lastLoaded = &_objLoader private
Pointer to the last used loader.
Referenced by geometry(), loadModel(), and material().
_loaders
std::unordered_map<std::string, loaders::ILoader *> model_viewer::ModelManager::_loaders private
Initial value:
= {
        {".obj", &_objLoader},
    }
Map of file extensions to their respective loaders.
{
        {".obj", &_objLoader},
    };
Referenced by loadModel().
_loading
bool model_viewer::ModelManager::_loading = false private
Boolean indicating if a model is currently loading.
Referenced by isLoading(), and setLoading().
_objLoader
loaders::ObjLoader model_viewer::ModelManager::_objLoader private
OBJ loader instance.
_ready
bool model_viewer::ModelManager::_ready = false private
Boolean indicating if a model is ready.
Referenced by isReady(), and setReady().
Property Documentation
geometry
QQuick3DGeometry * model_viewer::ModelManager::geometry read
loading
bool model_viewer::ModelManager::loading read
material
model_viewer::material::MTLMaterial * model_viewer::ModelManager::material read
ready
bool model_viewer::ModelManager::ready read
The documentation for this class was generated from the following files:
/github/workspace/include/ModelManager.hpp
/github/workspace/src/ModelManager.cpp