ModelViewer: ObjLoader Class Reference
ObjLoader Class Reference final
#include <ObjLoader.hpp>
Public Member Functions
ObjLoader ()
~ObjLoader () override=default
void loadModel (const std::string &filepath) override
QQuick3DGeometry * geometry () const override
MTLMaterial * material () const override
Public Member Functions inherited from ILoader
virtual ~ILoader ()=default
Private Member Functions
void resetObj ()
void parseVertice (const std::string &line)
void parseNormal (const std::string &line)
void parseTextureCoordinate (const std::string &line)
void parseFace (const std::string &line)
FaceIndex parseFaceIndex (const std::string &token)
void retrieveMaterial (const std::string &line)
Private Attributes
std::vector< Vector3 > _vertices
std::vector< TextureCoordinate > _textureCoords
std::vector< Vector3 > _normals
std::vector< FaceIndex > _faces
std::string _modelPath
std::unordered_map< std::string, std::function< void(const std::string &)> > _parseFunctions
std::unique_ptr< ObjGeometry > _geometry
std::unique_ptr< MTLMaterial > _material
Constructor & Destructor Documentation
ObjLoader()
ObjLoader::ObjLoader ()
    : _geometry(new ObjGeometry()), _material(new MTLMaterial()) {
    _parseFunctions = {
        {"v", [this](const std::string &l) { parseVertice(l); }},
        {"vn", [this](const std::string &l) { parseNormal(l); }},
        {"vt", [this](const std::string &l) { parseTextureCoordinate(l); }},
        {"f", [this](const std::string &l) { parseFace(l); }},
        {"mtllib", [this](const std::string &l) { retrieveMaterial(l); }},
    };
}
References _parseFunctions, parseFace(), parseNormal(), parseTextureCoordinate(), parseVertice(), and retrieveMaterial().
~ObjLoader()
ObjLoader::~ObjLoader () override default
Member Function Documentation
geometry()
QQuick3DGeometry * ObjLoader::geometry () const inline override virtual
Implements ILoader.
{ return _geometry.get(); };
References _geometry.
loadModel()
void ObjLoader::loadModel (const std::string & filepath) override virtual
Implements ILoader.
{
    resetObj();
    _material->resetMaterial();
    _modelPath = filepath;
    std::ifstream in(filepath);
    if (!in.is_open()) {
        std::cerr << "Could not open file " << filepath << ": "
                  << std::strerror(errno) << std::endl;
        return;
    }
    std::string line;
    while (std::getline(in, line)) {
        const auto pos = line.find(' ');
        const std::string lineStart = trim_copy(line.substr(0, pos));
        if (_parseFunctions.contains(lineStart))
            _parseFunctions.at(lineStart)(line);
    }
    std::vector<Vector3> v;
    std::vector<TextureCoordinate> vt;
    std::vector<Vector3> vn;
    for (auto f : _faces) {
        if (!_vertices.empty() && f.v != 0) {
            const int vIdx = f.v > 0 ? f.v - 1 : v.size() + f.v;
            v.push_back(_vertices[vIdx]);
        }
        if (!_textureCoords.empty() && f.vt != 0) {
            const int vtIdx = f.vt > 0 ? f.vt - 1 : v.size() + f.vt;
            vt.push_back(_textureCoords[vtIdx]);
        }
        if (!_normals.empty() && f.vn != 0) {
            const int vnIdx = f.vn > 0 ? f.vn - 1 : v.size() + f.vn;
            vn.push_back(_normals[vnIdx]);
        }
    }
    _vertices = v;
    _textureCoords = vt;
    _normals = vn;
    _geometry->setMesh(_vertices, _normals, _textureCoords);
}
References _faces, _geometry, _material, _modelPath, _normals, _parseFunctions, _textureCoords, _vertices, resetObj(), and trim_copy().
material()
MTLMaterial * ObjLoader::material () const inline override virtual
Implements ILoader.
{ return _material.get(); };
References _material.
parseFace()
void ObjLoader::parseFace (const std::string & line) private
{
    std::istringstream f(line.substr(2));
    std::string token;
    std::vector<FaceIndex> face;
    while (f >> token) face.push_back(parseFaceIndex(token));
    for (size_t i = 1; i + 1 < face.size(); ++i) {
        this->_faces.push_back(face[0]);
        this->_faces.push_back(face[i]);
        this->_faces.push_back(face[i + 1]);
    }
}
References _faces, and parseFaceIndex().
Referenced by ObjLoader().
parseFaceIndex()
FaceIndex ObjLoader::parseFaceIndex (const std::string & token) private
{
    FaceIndex idx;
    std::sscanf(token.c_str(), "%d/%d/%d", &idx.v, &idx.vt, &idx.vn);
    if (token.find("//") != std::string::npos) {
        std::sscanf(token.c_str(), "%d//%d", &idx.v, &idx.vn);
        idx.vt = 0;
    } else if (token.find('/') != std::string::npos &&
               std::ranges::count(token, '/') == 1) {
        std::sscanf(token.c_str(), "%d/%d", &idx.v, &idx.vt);
        idx.vn = 0;
    } else if (token.find('/') == std::string::npos) {
        std::sscanf(token.c_str(), "%d", &idx.v);
    }
    return idx;
}
References FaceIndex::v, FaceIndex::vn, and FaceIndex::vt.
Referenced by parseFace().
parseNormal()
void ObjLoader::parseNormal (const std::string & line) private
{
    float x, y, z;
    if (std::sscanf(line.c_str() + 2, "%f %f %f", &x, &y, &z) < 3)
        std::cerr << "Invalid normal at line " << line << std::endl;
    else
        this->_normals.push_back({x, y, z});
}
References _normals.
Referenced by ObjLoader().
parseTextureCoordinate()
void ObjLoader::parseTextureCoordinate (const std::string & line) private
{
    float u, v;  // Missing w
    if (std::sscanf(line.c_str() + 2, "%f %f", &u, &v) < 2)
        std::cerr << "Invalid normal at line " << line << std::endl;
    else
        this->_textureCoords.push_back({u, v});
}
References _textureCoords.
Referenced by ObjLoader().
parseVertice()
void ObjLoader::parseVertice (const std::string & line) private
{
    float x, y, z;  // Missing optional w
    if (std::sscanf(line.c_str() + 2, "%f %f %f", &x, &y, &z) < 3)
        std::cerr << "Invalid vertice at line " << line << std::endl;
    else
        this->_vertices.push_back({x, y, z});
}
References _vertices.
Referenced by ObjLoader().
resetObj()
void ObjLoader::resetObj () private
{
    _faces.clear();
    _vertices.clear();
    _normals.clear();
    _textureCoords.clear();
}
References _faces, _normals, _textureCoords, and _vertices.
Referenced by loadModel().
retrieveMaterial()
void ObjLoader::retrieveMaterial (const std::string & line) private
{
    const std::string name = trim_copy(line.substr(sizeof("mtllib")));
    const std::filesystem::path path =
        std::filesystem::path(_modelPath).parent_path() / name;
    _material->parseMTL(path.string());
}
References _material, _modelPath, and trim_copy().
Referenced by ObjLoader().
Member Data Documentation
_faces
std::vector<FaceIndex> ObjLoader::_faces private
Referenced by loadModel(), parseFace(), and resetObj().
_geometry
std::unique_ptr<ObjGeometry> ObjLoader::_geometry private
Referenced by geometry(), and loadModel().
_material
std::unique_ptr<MTLMaterial> ObjLoader::_material private
Referenced by loadModel(), material(), and retrieveMaterial().
_modelPath
std::string ObjLoader::_modelPath private
Referenced by loadModel(), and retrieveMaterial().
_normals
std::vector<Vector3> ObjLoader::_normals private
Referenced by loadModel(), parseNormal(), and resetObj().
_parseFunctions
std::unordered_map<std::string, std::function<void(const std::string &)> > ObjLoader::_parseFunctions private
Referenced by loadModel(), and ObjLoader().
_textureCoords
std::vector<TextureCoordinate> ObjLoader::_textureCoords private
Referenced by loadModel(), parseTextureCoordinate(), and resetObj().
_vertices
std::vector<Vector3> ObjLoader::_vertices private
Referenced by loadModel(), parseVertice(), and resetObj().
The documentation for this class was generated from the following files:
/github/workspace/include/ObjLoader.hpp
/github/workspace/src/ObjLoader.cpp