ModelViewer: model_viewer::string_helpers Namespace Reference
model_viewer::string_helpers Namespace Reference
Functions
void ltrim (std::string &s)
Trim from the start (in place)
void rtrim (std::string &s)
Trim from the end (in place)
void trim (std::string &s)
Trim from both ends (in place)
std::string ltrim_copy (std::string s)
Trim from the start (copying)
std::string rtrim_copy (std::string s)
Trim from the end (copying)
std::string trim_copy (std::string s)
Trim from both ends (copying)
std::string normalizePath (std::string p)
Normalize a file path by removing "file://" scheme and leading slash on Windows paths.
Function Documentation
ltrim()
void model_viewer::string_helpers::ltrim (std::string & s) inline
Trim from the start (in place)
Parameters
s String to trim
{
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](unsigned char ch) {
                return !std::isspace(ch);
            }));
}
Referenced by ltrim_copy(), and trim().
ltrim_copy()
std::string model_viewer::string_helpers::ltrim_copy (std::string s) inline
Trim from the start (copying)
Parameters
s String to trim
Returns
Trimmed string
{
    ltrim(s);
    return s;
}
References ltrim().
normalizePath()
std::string model_viewer::string_helpers::normalizePath (std::string p) inline
Normalize a file path by removing "file://" scheme and leading slash on Windows paths.
Parameters
p Path to normalize
Returns
Normalized path
{
    const std::string fileScheme = "file://";
    if (p.rfind(fileScheme, 0) == 0) {
        p.erase(0, fileScheme.size());
    }
    if (p.size() >= 3 && p[0] == '/' &&
        std::isalpha(static_cast<unsigned char>(p[1])) && p[2] == ':') {
        p.erase(0, 1);
    }
    return p;
}
Referenced by model_viewer::loaders::ObjLoader::loadModel().
rtrim()
void model_viewer::string_helpers::rtrim (std::string & s) inline
Trim from the end (in place)
Parameters
s String to trim
{
    s.erase(std::find_if(s.rbegin(), s.rend(),
                         [](unsigned char ch) { return !std::isspace(ch); })
                .base(),
            s.end());
}
Referenced by rtrim_copy(), and trim().
rtrim_copy()
std::string model_viewer::string_helpers::rtrim_copy (std::string s) inline
Trim from the end (copying)
Parameters
s String to trim
Returns
Trimmed string
{
    rtrim(s);
    return s;
}
References rtrim().
trim()
void model_viewer::string_helpers::trim (std::string & s) inline
Trim from both ends (in place)
Parameters
s String to trim
{
    rtrim(s);
    ltrim(s);
}
References ltrim(), and rtrim().
Referenced by trim_copy().
trim_copy()
std::string model_viewer::string_helpers::trim_copy (std::string s) inline
Trim from both ends (copying)
Parameters
s String to trim
Returns
Trimmed string
{
    trim(s);
    return s;
}
References trim().
Referenced by model_viewer::loaders::ObjLoader::loadModel(), model_viewer::material::MTLMaterial::parseColor(), model_viewer::material::MTLMaterial::parseMap(), model_viewer::material::MTLMaterial::parseMTL(), model_viewer::material::MTLMaterial::parseScalar(), and model_viewer::loaders::ObjLoader::retrieveMaterial().