ModelViewer: /github/workspace/include/StringHelpers.hpp File Reference
StringHelpers.hpp File Reference
#include <algorithm>
#include <cctype>
#include <locale>
Functions
void ltrim (std::string &s)
void rtrim (std::string &s)
void trim (std::string &s)
std::string ltrim_copy (std::string s)
std::string rtrim_copy (std::string s)
std::string trim_copy (std::string s)
Function Documentation
ltrim()
void ltrim (std::string & s) inline
{
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](unsigned char ch) {
                return !std::isspace(ch);
            }));
}
Referenced by ltrim_copy(), and trim().
ltrim_copy()
std::string ltrim_copy (std::string s) inline
{
    ltrim(s);
    return s;
}
References ltrim().
rtrim()
void rtrim (std::string & s) inline
{
    s.erase(std::find_if(s.rbegin(), s.rend(),
                         [](unsigned char ch) { return !std::isspace(ch); })
                .base(),
            s.end());
}
Referenced by rtrim_copy(), and trim().
rtrim_copy()
std::string rtrim_copy (std::string s) inline
{
    rtrim(s);
    return s;
}
References rtrim().
trim()
void trim (std::string & s) inline
{
    rtrim(s);
    ltrim(s);
}
References ltrim(), and rtrim().
Referenced by trim_copy().
trim_copy()
std::string trim_copy (std::string s) inline
{
    trim(s);
    return s;
}
References trim().
Referenced by ObjLoader::loadModel(), MTLMaterial::parseColor(), MTLMaterial::parseMap(), MTLMaterial::parseMTL(), MTLMaterial::parseScalar(), and ObjLoader::retrieveMaterial().